name: my_ci

on:
  push:
    branches:
      - master

jobs:
  my_testing:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: run_script
      run: echo run my_ci
      name: run script
      run: echo @new_actions_to_build
  my_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: print github actions
      
      
